/*  =========================================================================
    global domination - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of Global Domination. Resistance is useless.
    ​
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef GDOM_LIBRARY_H_INCLUDED
#define GDOM_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  GDOM version macros for compile-time API detection
#define GDOM_VERSION_MAJOR 0
#define GDOM_VERSION_MINOR 2
#define GDOM_VERSION_PATCH 0

#define GDOM_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define GDOM_VERSION \
    GDOM_MAKE_VERSION(GDOM_VERSION_MAJOR, GDOM_VERSION_MINOR, GDOM_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined GDOM_STATIC
#       define GDOM_EXPORT
#   elif defined GDOM_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define GDOM_EXPORT __declspec(dllexport)
#       else
#           define GDOM_EXPORT
#       endif
#   elif defined GDOM_EXPORTS
#       define GDOM_EXPORT __declspec(dllexport)
#   else
#       define GDOM_EXPORT __declspec(dllimport)
#   endif
#   define GDOM_PRIVATE
#elif defined (__CYGWIN__)
#   define GDOM_EXPORT
#   define GDOM_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define GDOM_PRIVATE __attribute__ ((visibility ("hidden")))
#       define GDOM_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define GDOM_PRIVATE
#       define GDOM_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  GDOM_BUILD_DRAFT_API
#define GDOM_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef GDOM_BUILD_DRAFT_API
typedef struct _gdom_server_t gdom_server_t;
#define GDOM_SERVER_T_DEFINED
typedef struct _gdom_client_t gdom_client_t;
#define GDOM_CLIENT_T_DEFINED
#endif // GDOM_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef GDOM_BUILD_DRAFT_API
#include "gdom_server.h"
#include "gdom_client.h"
#endif // GDOM_BUILD_DRAFT_API

#ifdef GDOM_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
GDOM_EXPORT void
    gdom_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // GDOM_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
